sudo: false
language: cpp
env:
  - COMPILER=gcc
  - COMPILER=clang
  - COMPILER=arduino VERSION=1.5.8 BOARD=arduino:avr:uno
  - COMPILER=arduino VERSION=1.6.7 BOARD=arduino:avr:uno
script: scripts/travis/$COMPILER.sh
